'use client';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../styles/extra.css"
import { AppProgressBar as ProgressBar } from 'next-nprogress-bar';
import Home from "./page";
const inter = Inter({ subsets: ["latin"] });
import navLink from "../constant/nav"
import Link from "next/link";
import Typewriter from 'typewriter-effect'
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="mx-auto max-w-3xl px-4 sm:px-6 xl:max-w-5xl xl:px-0">
        <div className="flex w-full justify-between py-10">
          <div>
            <Link href="/">
              <div className="text-primary-color dark:text-primary-color-dark flex items-center justify-between text-xl font-semibold">
                {`~/`}{' '}
                <Typewriter
                  options={{
                    strings: [],
                    autoStart: true,
                    loop: true,
                  }}
                />
              </div>
            </Link>
          </div>
          <div className="flex items-center text-base leading-5">
            <div className="hidden sm:block">
              {navLink.map((link) => (
                <Link
                  key={link.title}
                  href={link.href as string}
                  className="link-underline rounded py-1 px-2 text-gray-900 hover:bg-gray-200 dark:text-gray-100 dark:hover:bg-gray-700 sm:py-2 sm:px-3"
                >
                  {link.title}
                </Link>
              ))}
            </div>
            {/* <CommandPalette navigation={navigation} />
          <ThemeSwitch />
          <DropMenu /> */}
            {/* <MobileNav /> */}
          </div>
        </div>
        2
        <ProgressBar
          height="2px"
          color="#DE1D8D"
          options={{ showSpinner: false }}
          shallowRouting
        />
        <Home>{children}</Home>
      </body>
    </html>
  );
}
